INCLUDE(${PROJECT_SOURCE_DIR}/cmake/internal/Utils.cmake)
INCLUDE(${PROJECT_SOURCE_DIR}/cmake/internal/AnsiColor.cmake)
IF("x${PROJECT_SCRIPTS_DIR}" STREQUAL "x")
  SET(PROJECT_SCRIPTS_DIR ${PROJECT_SOURCE_DIR}/scripts)
  VERBOSE_MESSAGE("scripts 目录: " ${PROJECT_SCRIPTS_DIR})
ENDIF()
# 可以在这里配置拉取依赖 或者执行一些命令
MESSAGE(STATUS "${BW}正在使用的编译器是: ${BN}${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}${COLOR_OFF}")