FUNCTION(VERBOSE_MESSAGE maybe_a_list)
  # 检查 prefix 参数是否被提供，如果没有提供则设置为空字符串
  SET(prefix "")
  IF(ARGC GREATER 1)
    SET(prefix "${ARGV0}")
    SET(maybe_a_list "${ARGV1}")
  ELSE()
    SET(maybe_a_list "${ARGV0}")
  ENDIF()
  IF(${PROJECT_NAME}_VERBOSE_OUTPUT)
    FOREACH(item IN LISTS maybe_a_list)
      MESSAGE(STATUS "${G}${prefix}${item}${COLOR_OFF}")
    ENDFOREACH()
  ENDIF()
endfunction()
